'use client';
import Link from 'next/link';
import {useState,useEffect,useRef} from 'react';
import {usePathname} from 'next/navigation';
import {sitePath} from '@/lib/paths';
import {MarketTicker} from './markets';
import customPages from '@/data/pages.json';
import {Search,Menu,Radio,ChevronDown,ChevronRight,TvMinimal,CloudSun,Rss} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetTrigger} from '@/components/ui/sheet';
import {categories,districts} from '@/data/news';
export function Brand({inverse=false}:{inverse?:boolean}){return <Link href="/" className={'brand '+(inverse?'inverse':'')} aria-label="Eskişehir Masası ana sayfa"><img className="brand-symbol" src={sitePath("/brand-symbol.png")} alt=""/><span className="brand-name">eskişehir<span>masası<span className="brand-period">.</span></span></span></Link>}
export function Header(){const [search,setSearch]=useState(false);const [open,setOpen]=useState(false);return <><MarketTicker/><div className="utility"><div className="container utility-inner"><div><Link href="/son-dakika">Son Dakika</Link><span className="utility-sep"/>{districts.slice(0,5).map(d=><Link key={d[0]} href={'/ilceler/'+d[0]}>{d[1]}</Link>)}</div><Link href="/sayfa/resmi-ilanlar">Resmî İlanlar</Link></div></div><header className="masthead container"><Brand/><div className="masthead-middle"><span className="edition">ŞEHRİN GÜNDEMİ, AYNI MASADA.</span><span>Yerelden dünyaya, Eskişehir’den bakış.</span></div><div className="masthead-actions"><Link href="/sayfa/hava-durumu" className="weather"><CloudSun size={24}/><span>Eskişehir<small>Hava durumu</small></span></Link><Link href="/canli-yayin" className="live-button"><Radio size={17}/> CANLI YAYIN</Link></div></header><div className="nav-wrap"><nav className="container main-nav" aria-label="Ana menü"><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="menu-button" aria-label="Tüm kategorileri aç"><Menu size={22}/></button></SheetTrigger><SheetContent side="left" className="drawer"><SheetTitle className="drawer-title">Eskişehir Masası</SheetTitle><div className="drawer-links" onClick={()=>setOpen(false)}><Link href="/">Ana Sayfa</Link><Link href="/son-dakika">Son Dakika</Link>{categories.map(c=><Link key={c[0]} href={'/kategori/'+c[0]}>{c[1]}</Link>)}<details className="drawer-districts" onClick={e=>e.stopPropagation()}><summary>İlçeler</summary><div onClick={()=>setOpen(false)}><Link href="/ilceler">Tüm ilçeler</Link>{districts.map(d=><Link key={d[0]} href={"/ilceler/"+d[0]}>{d[1]}</Link>)}</div></details><Link href="/foto-galeri">Foto Galeri</Link><Link href="/videolar">Videolar</Link><Link href="/canli-yayin">Canlı Yayın</Link><Link href="/sayfa/sehir-rehberi">Şehir Rehberi</Link><a href="https://deprem.afad.gov.tr/" target="_blank" rel="noopener noreferrer">Son Depremler</a><Link href="/sayfa/hava-durumu">Hava Durumu</Link><a href="/rss.xml">RSS</a></div></SheetContent></Sheet><DistrictMenu/><div className="nav-links">{categories.slice(0,12).map(c=><Link key={c[0]} href={'/kategori/'+c[0]}>{c[1]}</Link>)}</div><button className="search-toggle" aria-label="Haber ara" aria-expanded={search} onClick={()=>setSearch(!search)}><Search size={21}/></button></nav></div>{search&&<div className="search-bar"><form action="/ara" className="container"><Search size={22}/><input name="q" placeholder="Haber, ilçe veya konu arayın…" aria-label="Aranacak haber" autoFocus required/><button type="submit">Ara</button><button type="button" className="text-button" onClick={()=>setSearch(false)}>Kapat</button></form></div>}</>}
export function Footer(){return <footer><div className="container"><div className="footer-top"><Brand inverse/><p>Eskişehir’in gündemini birlikte takip ediyoruz.</p><Link href="/canli-yayin"><TvMinimal size={23}/> Eskişehir Masası TV</Link></div><div className="footer-columns"><div><h3>HABERLER</h3><div className="footer-grid">{categories.map(c=><Link key={c[0]} href={'/kategori/'+c[0]}>{c[1]}</Link>)}</div></div><div><h3>İLÇELER</h3><div className="footer-grid">{districts.map(c=><Link key={c[0]} href={'/ilceler/'+c[0]}>{c[1]}</Link>)}</div></div><div><h3>ESKİŞEHİR MASASI</h3><div className="footer-grid single">{[['kunye','Künye'],['iletisim','İletişim'],['yayin-ilkeleri','Yayın İlkeleri'],['gizlilik','Gizlilik ve Veri Politikası'],['cerez-politikasi','Çerez Politikası'],['yorum-kurallari','Yorum Kuralları'],['okur-temsilcisi','Okur Temsilcisi'],['duzeltme','Düzeltme ve Yanıt Hakkı'],...Object.entries(customPages).filter(([slug])=>!['kunye','iletisim','yayin-ilkeleri','gizlilik','cerez-politikasi','yorum-kurallari','okur-temsilcisi','duzeltme'].includes(slug)).map(([slug,p])=>[slug,(p as {title:string}).title])].map(c=><Link key={c[0]} href={'/sayfa/'+c[0]}>{c[1]}</Link>)}</div></div></div><div className="footer-bottom"><span>© 2026 Eskişehir Masası</span><Link href="/yonetim">Yönetim</Link><span>Haberlerde özgün kurum kaynakları belirtilmiştir.</span><a href="/rss.xml"><Rss size={15}/> RSS</a></div></div></footer>}

function DistrictMenu(){const [expanded,setExpanded]=useState(false);const ref=useRef<HTMLDivElement>(null);const path=usePathname();useEffect(()=>setExpanded(false),[path]);useEffect(()=>{const close=(e:MouseEvent)=>{if(!ref.current?.contains(e.target as Node))setExpanded(false)};document.addEventListener('click',close);return()=>document.removeEventListener('click',close)},[]);return <div className="district-menu" ref={ref} onKeyDown={e=>{if(e.key==='Escape'){setExpanded(false);ref.current?.querySelector('button')?.focus()}}}><button onClick={()=>setExpanded(!expanded)} aria-expanded={expanded} aria-controls="district-navigation">İlçeler <ChevronDown size={15}/></button>{expanded&&<div id="district-navigation" className="district-dropdown"><Link href="/ilceler" onClick={()=>setExpanded(false)}>Tüm ilçe haberleri <ChevronRight size={15}/></Link><div>{districts.map(([slug,label])=><Link key={slug} href={'/ilceler/'+slug} onClick={()=>setExpanded(false)}>{label}</Link>)}</div></div>}</div>}
export function SiteChrome({children}:{children:React.ReactNode}){const path=usePathname();return path?.startsWith('/yonetim')?<>{children}</>:<><Header/>{children}<Footer/></>}
