'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ChevronRight,MapPin} from 'lucide-react';
import {Article,districts,shortDate,categoryName} from '@/data/news';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export {Hero} from './hero';
export function LatestTabs({articles,count=6}:{articles:Article[];count?:number}){return <Tabs defaultValue="latest" className="latest-tabs"><TabsList className="latest-tab-list" variant="line"><TabsTrigger value="latest">Son Haberler</TabsTrigger><TabsTrigger value="featured">Öne Çıkanlar</TabsTrigger></TabsList>{['latest','featured'].map(t=><TabsContent value={t} key={t}><div className="latest-list">{(t==='latest'?articles:articles.filter(a=>a.featured)).slice(0,count).map((a,i)=><Link href={'/haber/'+a.slug} key={a.id}><span className="latest-number">{String(i+1).padStart(2,'0')}</span><div><small>{shortDate(a.date)} · {categoryName(a.categories[1]||'eskisehir')}</small><h3>{a.title}</h3></div></Link>)}</div><Link href="/son-dakika" className="all-latest">Haber akışını görüntüle <ChevronRight size={16}/></Link></TabsContent>)}</Tabs>}
export function DistrictFilter({articles}:{articles:Article[]}){const [district,setDistrict]=useState('all');const list=(district==='all'?articles.filter(a=>a.district!=='eskisehir'):articles.filter(a=>a.district===district)).slice(0,3);return <><div className="district-select-row"><div className="district-pills">{[['all','Tüm ilçeler'],...districts.slice(0,4)].map(d=><button key={d[0]} onClick={()=>setDistrict(d[0])} className={district===d[0]?'active':''} aria-pressed={district===d[0]}>{d[1]}</button>)}</div><Select value={district} onValueChange={setDistrict}><SelectTrigger aria-label="İlçe seçin"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Tüm ilçeler</SelectItem>{districts.map(d=><SelectItem key={d[0]} value={d[0]}>{d[1]}</SelectItem>)}</SelectContent></Select></div><div className="district-news-grid">{list.map(a=><Link href={'/haber/'+a.slug} key={a.id}><img src={a.image} alt="" loading="lazy"/><div><span className="eyebrow"><MapPin size={12}/>{districts.find(d=>d[0]===a.district)?.[1]||'Eskişehir'}</span><h3>{a.title}</h3><small>{shortDate(a.date)}</small></div></Link>)}</div>{!list.length&&<p className="empty-inline">Bu ilçe için henüz bir haber eklenmedi. <Link href={'/ilceler/'+district}>İlçenin resmi kaynaklarını inceleyin.</Link></p>}</>}
