'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ChevronLeft,ChevronRight,MapPin} from 'lucide-react';
import {Article,districts,shortDate,categoryName} from '@/data/news';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export function Hero({items}:{items:Article[]}){const [index,setIndex]=useState(0);const a=items[index];if(!a)return null;return <div className="hero"><Link className="hero-story" href={'/haber/'+a.slug}>{a.image&&<img src={a.image} alt={a.title} fetchPriority="high"/>}<div className="hero-shade"/><div className="hero-copy"><span className="hero-category">{categoryName(a.categories.find(c=>c!=='eskisehir')||'eskisehir')}</span><h2>{a.title}</h2><p>{a.summary}</p><span className="hero-meta">{shortDate(a.date)} <i/> {a.source}</span></div></Link><div className="hero-controls"><div className="hero-pages">{items.map((item,i)=><button key={item.id} onClick={()=>setIndex(i)} className={index===i?'active':''} aria-label={(i+1)+'. manşet'} aria-pressed={index===i}>{String(i+1).padStart(2,'0')}</button>)}</div><div className="hero-arrows"><button aria-label="Önceki manşet" onClick={()=>setIndex((index+items.length-1)%items.length)}><ChevronLeft size={20}/></button><button aria-label="Sonraki manşet" onClick={()=>setIndex((index+1)%items.length)}><ChevronRight size={20}/></button></div></div></div>}
export function LatestTabs({articles}:{articles:Article[]}){return <Tabs defaultValue="latest" className="latest-tabs"><TabsList className="latest-tab-list" variant="line"><TabsTrigger value="latest">Son Haberler</TabsTrigger><TabsTrigger value="featured">Öne Çıkanlar</TabsTrigger></TabsList>{['latest','featured'].map(t=><TabsContent value={t} key={t}><div className="latest-list">{(t==='latest'?articles:articles.filter(a=>a.featured)).slice(0,6).map((a,i)=><Link href={'/haber/'+a.slug} key={a.id}><span className="latest-number">{String(i+1).padStart(2,'0')}</span><div><small>{shortDate(a.date)} · {categoryName(a.categories[1]||'eskisehir')}</small><h3>{a.title}</h3></div></Link>)}</div><Link href="/son-dakika" className="all-latest">Haber akışını görüntüle <ChevronRight size={16}/></Link></TabsContent>)}</Tabs>}
export function DistrictFilter({articles}:{articles:Article[]}){const [district,setDistrict]=useState('all');const list=(district==='all'?articles.filter(a=>a.district!=='eskisehir'):articles.filter(a=>a.district===district)).slice(0,3);return <><div className="district-select-row"><div className="district-pills">{[['all','Tüm ilçeler'],...districts.slice(0,4)].map(d=><button key={d[0]} onClick={()=>setDistrict(d[0])} className={district===d[0]?'active':''}>{d[1]}</button>)}</div><Select value={district} onValueChange={setDistrict}><SelectTrigger aria-label="İlçe seçin"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Tüm ilçeler</SelectItem>{districts.map(d=><SelectItem key={d[0]} value={d[0]}>{d[1]}</SelectItem>)}</SelectContent></Select></div><div className="district-news-grid">{list.map(a=><Link href={'/haber/'+a.slug} key={a.id}><img src={a.image} alt="" loading="lazy"/><div><span className="eyebrow"><MapPin size={12}/>{districts.find(d=>d[0]===a.district)?.[1]||'Eskişehir'}</span><h3>{a.title}</h3><small>{shortDate(a.date)}</small></div></Link>)}</div>{!list.length&&<p className="empty-inline">Bu ilçe için henüz bir haber eklenmedi. <Link href={'/ilceler/'+district}>İlçenin resmi kaynaklarını inceleyin.</Link></p>}</>}
