import {ArticleBody} from '@/components/news/article-body';
import Link from 'next/link';
import {VideoPlayer} from '@/components/news/media';
import {notFound} from 'next/navigation';
import {articles,getArticle,categoryName,dateLabel,newest} from '@/data/news';
import {Breadcrumbs} from '@/components/news/listing';
import {LatestTabs} from '@/components/news/widgets';
import {LiveCard,NewsCard,SectionHeading} from '@/components/news/site';
import {Share,Engagement} from '@/components/news/engagement';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const a=getArticle((await params).slug);return {title:a?.seoTitle||a?.title||'Haber bulunamadı',description:a?.seoDescription||a?.summary};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const a=getArticle((await params).slug);if(!a)notFound();const category=a.categories.find(c=>c!=='eskisehir')||'eskisehir';const related=articles.filter(b=>b.id!==a.id&&b.categories.some(c=>c!=='eskisehir'&&a.categories.includes(c))).slice(0,3);return <main id="icerik" className="container page-content"><Breadcrumbs label="Haber" parent={{label:categoryName(category),href:'/kategori/'+category}}/><div className="article-layout"><article><header className="article-head"><span className="eyebrow">{categoryName(category)}</span><h1>{a.title}</h1><p className="article-deck">{a.summary}</p><div className="article-byline"><div className="byline-left"><span className="source-avatar">EM</span><div><b>Eskişehir Masası</b><small>Kaynak: {a.source}</small></div></div><span>{dateLabel(a.date)}<br/>{Math.max(1,Math.ceil(a.body.join(' ').split(' ').length/180))} dk okuma</span></div></header><figure><img className="article-photo" src={a.image} alt={a.title}/><figcaption className="photo-credit">Fotoğraf: {a.imageCredit||a.source}</figcaption></figure><Share title={a.title}/>{a.isArchive&&<div className="info-box"><p>Arşiv haberi · Bu içerik {dateLabel(a.date)} tarihindeki gelişmeyi aktarır.</p></div>}<div className="article-summary"><strong>HABERİN ÖZETİ</strong><p>{a.summary}</p></div><ArticleBody paragraphs={a.body}/>{a.videoId&&<VideoPlayer youtubeId={a.videoId} title={a.title}/>}<div className="source-box"><div><b>{a.source}</b><small>{a.sourceUrl?"Kurumun "+dateLabel(a.date)+" tarihli açıklamasından derlenmiştir.":"Eskişehir Masası yayını."}</small></div>{a.sourceUrl&&<a href={a.sourceUrl} target="_blank" rel="noopener noreferrer">Özgün haberi oku</a>}</div><div className="tags">{a.categories.map(c=><Link href={'/kategori/'+c} key={c}>#{categoryName(c)}</Link>)}</div><Engagement articleId={a.id}/><section className="related-section"><SectionHeading title="İlginizi çekebilir"/><div className="three-grid">{related.map(b=><NewsCard key={b.id} article={b} small/>)}</div></section></article><aside><LiveCard/><div style={{marginTop:30}}><LatestTabs articles={newest()}/></div></aside></div></main>}
