import Link from 'next/link';
import env from '@/data/live.json';
import {sitePath} from '@/lib/paths';
import {Radio,Play} from 'lucide-react';
import {Breadcrumbs} from '@/components/news/listing';
import {VideoPlayer} from '@/components/news/media';
import videos from '@/data/videos.json';
export const metadata={title:'Canlı Yayın | Eskişehir Masası TV'};

export default function Page(){const values=env as unknown as Record<string,string>;const video=/^[\w-]{11}$/.test(values.YOUTUBE_LIVE_VIDEO_ID||'')?values.YOUTUBE_LIVE_VIDEO_ID:'';const channel=/^UC[\w-]{22}$/.test(values.YOUTUBE_CHANNEL_ID||'')?values.YOUTUBE_CHANNEL_ID:'';return <main id="icerik" className="container page-content"><Breadcrumbs label="Canlı Yayın"/><div className="page-heading"><span className="eyebrow">ESKİŞEHİR MASASI TV</span><h1>Eskişehir’in canlı yayın masası</h1><p>Şehrin gündemi, söyleşiler ve sahadan gelişmeler.</p></div><div className="live-page-grid"><div>{video?<VideoPlayer youtubeId={video} title="Eskişehir Masası canlı yayını"/>:channel?<div className="live-main-player"><iframe src={'https://www.youtube.com/embed/live_stream?channel='+channel} title="Eskişehir Masası canlı yayını" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/></div>:<div className="live-main-player"><div><img className="live-brand" src={sitePath("/brand-symbol.png")} alt="Eskişehir Masası"/><h2>Birazdan aynı masadayız.</h2><p>YouTube kanalımızın yayın hazırlıkları sürüyor. Canlı yayın başladığında buradan izleyebileceksiniz.</p></div></div>}<div className="live-description"><span className="off-air">{video||channel?'YOUTUBE YAYIN OYNATICISI':'YAYIN BEKLENİYOR'}</span><h2>Eskişehir Masası TV</h2><p>{video||channel?'Yayın, YouTube üzerinden bu ekranda izlenebilir.':'Şu anda aktif yayın bulunmuyor. Bu sırada şehrin video arşivini keşfedebilirsiniz.'}</p></div></div><aside className="program-card"><h2>Yayın akışı</h2><p>İlk yayın tarihi ve programı burada duyurulacak.</p><Link href="/videolar">Şehirden videoları izle</Link>{channel&&<p><a href={'https://www.youtube.com/channel/'+channel} target="_blank" rel="noopener noreferrer">YouTube kanalını aç</a></p>}</aside></div><section style={{marginTop:45}}><div className="section-heading"><h2>Yayın arası: Eskişehir’i keşfedin</h2><Link href="/videolar">Tüm videolar</Link></div><div className="two-grid">{videos.slice(0,2).map(v=><article className="video-entry" key={v.slug}><VideoPlayer youtubeId={'youtube_id'in v?v.youtube_id:undefined} videoUrl={v.video_url} poster={v.poster} title={v.title}/><h2>{v.title}</h2><p>{v.publisher}</p></article>)}</div></section></main>}
